#ifndef STATUS_H
#define STATUS_H

typedef enum
{
    STATUS_OK = 0,
    STATUS_INTEGER_INPUT_ERROR = 1,
    STATUS_INTEGER_OVERFLOW = 2,
    STATUS_FLOAT_INPUT_ERROR = 3,
    STATUS_FLOAT_OVERFLOW = 4,
    ERROR_SKIP_DELIMITERS = 5,
    STATUS_MISS_EXPONENT = 6,
    STATUS_MISS_SIGN = 7,
    STATUS_EXPONENT_INPUT_ERROR = 8,
    STATUS_EXPONENT_OVERFLOW_ERROR = 9
} return_code_t;

#endif
