#ifndef ERRORS_H
#define ERRORS_H

typedef enum {
    STATUS_NO_ERROR,
    STATUS_MENU_CHOICE_ERR,
    STATUS_CHOICE_LIMIT_ERROR,
    STATUS_FILE_OPEN_ERROR,
    STATUS_STRING_INPUT_ERROR,
    STATUS_NULL_POINTER_ERR,
    STATUS_TOKEN_ERROR,
    STATUS_KIND_FIELD_ERROR,
    STATUS_FILENAME_OVERFLOW,
    STATUS_RECORD_OVERFLOW,
    STATUS_FIELD_OVERFLOW,
    STATUS_NOT_FOUND_ERROR,
    STATUS_SPORT_INP_ERR,
    STATUS_CONTINENT_INP_ERR,
    STATUS_PRICE_INP_ERR,
    STATUS_FILE_WRITE_ERROR,
    STATUS_VISA_INP_ERROR,
} rc_t;

void print_error_msg(rc_t exit_code);

#endif
